---
title: "Leaflet Exploratory"
format: html
editor: visual
cache: TRUE
---

Load packages

```{r}
pacman::p_load('tidyverse', 
               'sf', 
               'here',
               'janitor',
               'tmap', 
               'kableExtra',
               'patchwork',
               'ggthemes',
               'colorRamps',
               'stars',
               'terra',
               'leaflet',
               'leaflet.extras',
               'leafem')
```

```{r}
source("/Users/petervitale/Desktop/MEDS/BirdWatch/Avian_GAP_Analysis/R/spatial_join.R")
```


```{r}
lifeform_colors <- c(
  CONIFER = "#74B162",
  HARDWOOD = "#A98858",
  HERBACEOUS = "#FEDD63",
  SHRUB = "#F7A54B",
  URBAN = "#595959",
  WATER = "#A2CDE6",
  AGRICULTURE = "#B5727A",
  "BARREN/OTHER" = "#FFCDDC"  
)

gap_colors <- c(
  '1' = '#244233',
  '2' = '#42765C',
  '3' = '#6FAE8F',
  '4' = '#CBE2D6',
  '5' = '#EFEFE7'
)

# Convert geometry to lat and long to create our points data frame
coords <- birds_joined %>% 
  st_transform(crs = 4326) %>% 
  st_coordinates()

leaflet_df <- birds_joined %>% 
  st_drop_geometry() %>% 
  cbind(coords) %>% 
  group_by(study_area, survey_type) %>% 
  summarize(area_observations = sum(observation_count),
         species = paste(unique(common_name), collapse = ", "),
         longitude = min(X),
         latitude = min(Y),
         gap_sts = min(gap_sts),
         habitat_type = paste(unique(habitat_type), collapse = ", "))

# confirm that data is in wgs84
gap_clean <- st_transform(gap_clean, crs = 4326)

habitat_poly <- st_transform(habitat_poly, crs = 4326)

# Set icon 
icon <- makeIcon(
  iconUrl = here::here('analysis','feather-pointed-solid.png'),
  iconWidth = 25, 
  iconHeight = 40
)

# Create color palettes
gap_pal <- colorFactor(
  palette = unname(gap_colors),  
  levels = names(gap_colors)
)


habitat_pal <- colorFactor(
  palette = unname(lifeform_colors),
  levels = names(lifeform_colors),
  na.color = "transparent"
)

# Map with colored polygons
leaflet_map <- leaflet() %>% 
  addProviderTiles(providers$Esri.WorldTerrain, group = "ESRI Terrain") %>% 
  addMiniMap(toggleDisplay = TRUE) %>% 
  
  # GAP Status with colors
  addPolygons(data = gap_clean, 
              group = 'GAP Status',
              fillColor = ~gap_pal(gap_sts),  # Replace gap_sts with your column
              color = "black", 
              weight = 1,
              fillOpacity = 1) %>% 
  
  # Vegetation Type with colors
  addPolygons(
  data = habitat_poly,           # need data = 
  group = 'Habitat Type',
  fillColor = ~habitat_pal(LIFEFORM),  # replace 'lifeform' with your actual column name
  color = "black",
  weight = 0.5,
  fillOpacity = 1
) %>%
  addMarkers(
  data = leaflet_df,
  lng = ~longitude,
  lat = ~latitude,
  icon = icon,
  popup = ~paste0(
    "<div style='max-height:200px; overflow-y:auto;'>",
    "<b>", study_area, "</b><br>",
    "<b> Survey Type: </b>", survey_type, "<br>",
    "<b> Habitat Type: </b>", habitat_type, "<br>",
    "<b> GAP Status: </b>", gap_sts, '<br>',
    "<b> Observations: </b>", area_observations, "<br>",
    "<b>Species:</b><br>", 
    gsub(", ", "<br>", species),  # Put each species on new line
    "</div>"
  ),
  popupOptions = popupOptions(maxWidth = 300),
  group = 'Observations'
) %>% 
    # Add legends
  addLegend(
    colors = lifeform_colors,
    labels = names(lifeform_colors),
    group = "Habitat Type",
    title = 'Habitat Type',
    position = 'bottomleft'
  ) %>% 
  addLegend(pal = gap_pal, 
            values = gap_clean$gap_sts,  # Replace with your column
            title = "GAP Status",
            position = "bottomleft",
            group = 'GAP Status') %>%
  
  addLayersControl(
    overlayGroups = c('GAP Status', 'Habitat Type', 'Observations'),
    options = layersControlOptions(collapsed = TRUE)
  ) %>% 
  
  leaflet.extras::addResetMapButton()

leaflet_map
```