---
title: "GLMM"
format: html
---
```{r}
library(tidyverse) # version 2.0.0
library(sf) #1.0-21
library(here) #1.0.1
library(janitor) #2.2.1
library(stars) #0.6-8
library(terra) #1.8-42
library(glmmTMB) #1.1.14
library(arcgislayers)
library(gtsummary)
library(gtExtras)

source(here("R", "spatial_join.R")
source(here('R', 'rich_gini.R'))

```

1. Aggregated biodiversity by Area Search
```{r}
# Obtain aggregated biodiversity data for Area Search
biodiv_area_search_agg <- birds_joined %>% 
  # Filter for only Area Search data
  filter(survey_type %in% "Area Search") %>% 
  # Run Gini Simpson function to obtain biodiversity values
  gini_simpson() %>% 
  # Add a column aggregating GAP Status by protection type
  mutate(protection = ifelse(gap_sts %in% c(1,2), 'Protected', 'Non-protected'))

# Pull out unique habitat types
habitats <- unique(biodiv_area_search_agg$habitat_type)

# Initialize list for each filtered habitat type
tmp <- vector(mode = 'list', length = 0)

# Initialize list for summary object of each model
area_agg <- vector(mode = 'list', length = 0)

# Run GLMM over each habitat type and fill in summary object
for (i in habitats){
  
  tmp[[i]] <- biodiv_area_search_agg %>% 
    st_drop_geometry() %>% 
    filter(habitat_type == i)
  
  
 area_agg[[i]] <- glmmTMB(rich_gini ~ protection, family = beta_family(), data = tmp[[i]])
}

```

2. Aggregated biodiversity by Point Count
```{r}
biodiv_point_count_agg <- birds_joined %>% 
  filter(survey_type %in% "Point Count") %>% 
  gini_simpson() %>% 
  mutate(protection = ifelse(gap_sts %in% c(1,2), 'Protected', 'Non-protected'))

habitats <- unique(biodiv_point_count_agg$habitat_type)
tmp <- vector(mode = 'list', length = 0)
point_agg <- vector(mode = 'list', length = 0)

for (i in habitats){
  
  tmp[[i]] <- biodiv_point_count_agg %>% 
    st_drop_geometry() %>% 
    filter(habitat_type == i)
  
  
  point_agg[[i]] <- glmmTMB(rich_gini ~ protection, family = beta_family(), data = tmp[[i]])
}

```

3. Non-aggregated biodiversity by Area Search

```{r}
biodiv_area_search_disag <- birds_joined %>% 
  filter(survey_type %in% "Area Search") %>% 
  gini_simpson()

habitats <- unique(biodiv_area_search_disag$habitat_type)
tmp <- vector(mode = 'list', length = 0)
area_disag <- vector(mode = 'list', length = 0)

for (i in habitats){
  
  tmp[[i]] <- biodiv_area_search_disag %>% 
    st_drop_geometry() %>% 
    filter(habitat_type == i)
  
  
  area_disag[[i]] <- glmmTMB(rich_gini ~ gap_sts, family = beta_family(), data = tmp[[i]])
}
```

4. Non-aggregated biodiversity by Point Count
```{r}
biodiv_point_count_disag <- birds_joined %>% 
  filter(survey_type %in% "Point Count") %>% 
  gini_simpson()

habitats <- unique(biodiv_point_count_disag$habitat_type)
tmp <- vector(mode = 'list', length = 0)
point_disag <- vector(mode = 'list', length = 0)

for (i in habitats){
  
  tmp[[i]] <-biodiv_point_count_disag %>% 
    st_drop_geometry() %>% 
    filter(habitat_type == i)
  
  
  point_disag[[i]] <- glmmTMB(rich_gini ~ gap_sts, family = beta_family(), data = tmp[[i]])
}

```
# Create model summary of aggregated biodiversity across point and area search

```{r}

birds_rich <- gini_simpson(birds_joined)

birds_rich <- birds_rich %>% 
  mutate(protection = ifelse(gap_sts %in% c(1,2), 'Protected', 'Non-protected'))

habitats <- unique(birds_rich$habitat_type)
tmp <- vector(mode = 'list', length = 0)
bird_summary <- vector(mode = 'list', length = 0)

for (i in habitats){
  
  tmp[[i]] <- birds_rich %>% 
    st_drop_geometry() %>% 
    filter(habitat_type == i)
  
  
  bird_summary[[i]] <- summary(glmmTMB(rich_gini ~ protection, family = beta_family(), data = tmp[[i]]))
}


```




```{r}
# Group summary mapping function across habitat types
habitat_names <- names(area_agg)

# Build a merged table (Area Search | Point Count) for each habitat
merged_by_habitat <- map(habitat_names, ~{
  tbl_merge(
    tbls = list(
      tbl_regression(area_agg[[.x]]),
      tbl_regression(point_agg[[.x]])
    ),
    tab_spanner = c("**Area Search**", "**Point Count**")
  )
})

# Stack all habitat tables with labels
aggregated_model_table <- tbl_stack(
  tbls = merged_by_habitat,
  group_header = habitat_names
)

# Apply table sty;ing
pointblue <- "#4495D1"
pointlightblue <- "#8EBEE0"

aggregated_model_table %>%
  as_gt() %>%
  tab_header(
    title = "Protection Status Effect on Biodiversity by Habitat Type"
  ) %>%
  tab_style(
    style = list(cell_fill(color = pointblue)),
    locations = cells_title()
  ) %>%
  tab_style(
    style = list(cell_fill(color = pointblue)),
    locations = cells_column_labels(everything())
  ) %>%
  tab_style(
    style = cell_fill(color = pointlightblue),
    locations = cells_body()
  ) %>%
  tab_style(
    style = list(cell_fill(color = pointblue)),
    locations = cells_row_groups()  # styles the habitat type headers
  ) %>%
  tab_source_note("Note: Models fit using glmmTMB with beta family.")

```

```{r}
merged_by_habitat_disag <- map(habitat_names, ~{
  tbl_merge(
    tbls = list(
      tbl_regression(area_disag[[.x]]),
      tbl_regression(point_disag[[.x]])
    ),
    tab_spanner = c("**Area Search**", "**Point Count**")
  )
})

# Stack all habitat tables with labels
disag_model_table <- tbl_stack(
  tbls = merged_by_habitat_disag,
  group_header = habitat_names
)

disag_model_table %>% 
  as_gt() %>%
  tab_header(
    title = "GAP Status Effect on Biodiversity by Habitat Type"
  ) %>%
  tab_style(
    style = list(cell_fill(color = pointblue)),
    locations = cells_title()
  ) %>%
  tab_style(
    style = list(cell_fill(color = pointblue)),
    locations = cells_column_labels(everything())
  ) %>%
  tab_style(
    style = cell_fill(color = pointlightblue),
    locations = cells_body()
  ) %>%
  tab_style(
    style = list(cell_fill(color = pointblue)),
    locations = cells_row_groups()  # styles the habitat type headers
  ) %>%
  tab_source_note("Note: Models fit using glmmTMB with beta family.")

```

