---
title: "technical_memo_figures"
format: html
---

## Load data and packages 
```{r}
library(sfarrow)
library(tidyverse)
library(here)
library(sf)
library(terra)
library(tigris)
library(tidyterra)
library(tmap)
library(janitor)
library(paletteer)
library(patchwork)
library(showtext)
library(kableExtra)

birds_joined <- st_read_parquet(here('data', 'data_processed', 
                                     'birds_joined.parquet'))

habitat_poly <- st_read_parquet(here('data','data_processed', 
                                     'habitat_polygon.parquet'))

gap_clean <- st_read_parquet(here('data','data_processed', 
                                  'gap_polygon.parquet'))
source(here("R", "point_blue_theme.R"))
showtext_auto(enable = TRUE)

```

## Observations by year

```{r}
# Where the data are, when, habitat and Gap? 

ggplot(birds_joined, aes(x = year_collected, y = sum(observation_count, na.rm = TRUE)))+
  geom_col()+
  theme_linedraw()+
  labs(y = 'Observations', 
       x = 'Year', 
       title = 'Observations by Year')+
  point_blue_theme()
```

Observations by year with density and area search/ point count 

```{r}

birds_joined %>%
  group_by(year_collected, survey_type) %>%
  summarise(observations = sum(observation_count, na.rm = TRUE), .groups = "drop") %>%
  ggplot(aes(
    x = year_collected,
    y = observations,
    color = survey_type,
    fill = survey_type,
    group = survey_type
  )) +
  geom_line() +
  geom_area(alpha = 0.5, position = "identity") +
  scale_fill_manual(values = c(point_blue, point_green)) +
  scale_color_manual(values = c(point_blue, point_green)) +
  scale_x_continuous(expand = c(0, 0)) +
  scale_y_continuous(
    expand = c(0, 0),
    label = scales::comma,
    limits = c(0, NA)
  ) +
  labs(
    title = "Avian Knowledge Network Bird Observations Over Time",
    subtitle = "Point count data is densely clustered 1995-2005",
    y = "Number of observations",
    x = NULL
  ) +
  point_blue_theme()


```


## Observations by gap status

```{r}
birds_joined %>% 
  group_by(gap_sts, survey_type) %>% 
  summarise(observations = sum(observation_count, na.rm = TRUE), .groups = "drop") %>% 
ggplot(aes(x = gap_sts, y = observations, color = survey_type,
    fill = survey_type,
    group = survey_type))+
  geom_col(position = "dodge")+
  scale_fill_manual(values = c(point_blue, point_green)) +
  scale_color_manual(values = c(point_blue, point_green)) +
  scale_y_continuous(
    expand = c(0, 0),
    label = scales::comma) +
  labs(y = 'Observations', 
       x = 'GAP Status', 
       title = 'Observations by GAP Status') +
  point_blue_theme() +
  annotate("segment", x = 6, xend = 6, y = 20000, yend = 170000) +
  annotate(geom = "text",
          x = 6, 
          y = 250000, 
          label = "observations \nin open water", 
          family = "lib_frank",
          size = 5
          )

```

## Observations by habitat type

```{r}
birds_joined %>% 
  group_by(habitat_type, survey_type) %>% 
  summarise(observations = sum(observation_count, na.rm = TRUE), .groups = "drop") %>% 
  mutate(habitat_type = reorder(habitat_type, observations)) %>% 
  ggplot(aes(x = observations, y = habitat_type, fill = habitat_type)) +
  geom_col() +
  scale_x_continuous(label = scales::comma) +
  scale_fill_manual(values = c(URBAN, AGRICULTURE, CONIFER, HERBACEOUS, SHRUB, HARDWOOD, WATER)) +
  scale_color_manual(values = c(URBAN, AGRICULTURE, CONIFER, HERBACEOUS, SHRUB, HARDWOOD, WATER)) +
  point_blue_theme() +
  theme(legend.position = "none") +
  labs(y = 'Observations', 
       x = 'Habitat Type', 
       title = 'Observations by Habitat')
```

## Observations by county 
```{r}
counties <- st_read(here::here('data','tl_2025_us_county', 
                               'tl_2025_us_county.shp')) %>% 
  clean_names() %>% 
  filter(statefp == '06') %>% 
  mutate(area = (aland+awater)* 1e-6) %>% 
  select(namelsad, area) %>% 
  st_transform(crs(birds_joined))

point_area_obs <- birds_joined %>% 
  select(observation_count) 
  

point_area_county <- st_join(counties, point_area_obs) %>% 
  st_drop_geometry() %>% 
  group_by(namelsad) %>% 
  summarize(total_observations = sum(observation_count))


point_area_county$total_observations[is.na(point_area_county$total_observations)] <-  0

county_obs <- left_join(counties, point_area_county,
                        by = 'namelsad')

county_obs <- county_obs %>% 
  group_by(namelsad) %>% 
  summarize(density = total_observations/area,
            total_obs = total_observations)

bluegreen <- colorRampPalette(colors = c('#4595D1', '#73B843'), bias = .5, space = 'Lab')

county_obs_plot <- ggplot(county_obs)+
  geom_sf(aes(fill = density))+
  scale_fill_gradientn(colors = bluegreen(100))+
  theme_void()+
  theme(legend.position = 'none')

ggsave(here('Outputs', 'figures', 'county_obs_plot.png'), county_obs_plot, scale = 1, width = 10, height = 10)
```

```{r}
other_names <- county_obs %>% 
  filter(total_obs == 0) %>% 
  st_drop_geometry() %>% 
  pull(namelsad)

county_obs_corrected <- county_obs %>% 
  filter(total_obs>0)

county_obs_corrected %>% 
  st_drop_geometry() %>% 
  arrange(desc(density))%>%
  rename('County Name' = namelsad,
         'Density' = density,
         'Total Observations' = total_obs) %>% 
  kable(format = "html", digits = 3, longtable = TRUE) %>% 
  kable_styling(
    bootstrap_options = c("striped", "hover", "condensed", "responsive"),
    full_width = FALSE,
    position = "center",
    font_size = 14
  ) %>% 
  footnote(general = paste("Dropped:", 
                           paste(other_names, collapse = ", "), 
                           'due to lack of observations')) %>% 
  row_spec(0, bold = TRUE, color = "black", background = "#4392CE") %>%
  row_spec(seq(1, nrow(county_obs_corrected), 2), 
           color = "black", 
           background = "#74B444") %>%
  row_spec(seq(2, nrow(county_obs_corrected), 2), color = "black", background = "#A8D175")%>%
  save_kable(here::here('Outputs', 'figures', "county_density_table.png"), zoom = 4)
```

## Habitat Complexity

```{r}
habitats <- tm_shape(habitat_poly) +
  tm_polygons(fill = 'LIFEFORM',
              fill.scale = tm_scale(
                values = c('#B5727A',
                           '#FF72DE',
                           '#74B162',
                           '#A98858',
                           '#FEDD63',
                           '#F7A54B',
                           '#595959',
                           '#8EBEE2')),
                lty = 'blank',
              fill.legend = tm_legend_hide())+
  tm_layout(bg = FALSE, frame = FALSE,
            outer.margins = 0)

tmap_save(habitats, here('Outputs', 'figures', 'habitats.png'), 
          bg = "transparent")
```

I want a plot of all the 47 habitat types

```{r}
habitats_full <- rast(here('data','fveg22_1.gdb'))


habitats_whrall <- tm_shape(habitats_full)+
  tm_raster(legend.show = FALSE)+
  tm_layout(bg = FALSE, frame = FALSE,
            outer.margins = 0)

tmap_save(habitats_whrall, here('Outputs', 'figures', 'habitats_whrall.png'), 
          bg = "transparent")
```


## Gap Plots

```{r}
california_shape <- tigris::states() %>% 
  filter(STUSPS == "CA")

bbox <- st_as_sfc(st_bbox(c(xmin = -128, xmax = -111, ymin = 29, ymax = 45), 
                          crs = st_crs(california_shape)))
mask <- st_difference(bbox, st_union(california_shape))
```

```{r}
gap1_2 <- tm_shape(mask, bbox = st_bbox(gap_clean)) +
  tm_polygons(fill = NA, col = NA) +
tm_basemap("Esri.WorldTopoMap")+
tm_shape(gap_clean %>% 
             filter(gap_sts %in% c(1,2)))+
  tm_polygons(fill = '#73B843',
              lty = 'blank',
              col = NA) +
  tm_layout(bg = FALSE, frame = FALSE,
            outer.margins = 0)

tmap_save(gap1_2, here('Outputs', 'figures', 'gap1_2.png'), 
          bg = "transparent")
```

```{r}
gap3_4 <- tm_shape(mask, bbox = st_bbox(gap_clean)) +
  tm_polygons(fill = NA, col = NA) +
tm_basemap("Esri.WorldTopoMap")+
tm_shape(gap_clean %>% 
             filter(gap_sts %in% c(3,4)))+
  tm_polygons(fill = '#F7A54B',
              lty = 'blank',
              col = NA) + 
  tm_layout(bg = FALSE, frame = FALSE)

tmap_save(gap3_4,here('Outputs', 'figures', 'gap3_4.png'),
          bg = "transparent")
```


```{r}
gap5 <- tm_shape(mask, bbox = st_bbox(gap_clean)) +
  tm_polygons(fill = NA, col = NA) +
tm_basemap("Esri.WorldTopoMap")+
tm_shape(gap_clean %>% 
             filter(gap_sts == 5))+
  tm_polygons(fill = charcoal,
              lty = 'blank',
              col = NA) + 
  tm_layout(bg = FALSE, frame = FALSE)

tmap_save(gap5, here('Outputs', 'figures', 'gap5.png'),
          bg = "transparent")
```

```{r}
basemap <- tm_shape(mask, bbox = st_bbox(gap_clean)) +
  tm_polygons(fill = NA, col = NA) +
  tm_basemap("Esri.WorldTopoMap")+
   tm_layout(bg = FALSE, frame = FALSE)

tmap_save(basemap,  here('Outputs', 'figures', 'basemap.png'),
          bg = "transparent")
```


## Table of cats

```{r}
# Source geodatabase from CAL FIRE
gdb_path <- here::here('data', 'ds1327', 'tiff', 'ds1327.tif')

# Create raster object for habitat type layer
habitat_type <- rast(gdb_path)

# Grab categories
cats <- cats(habitat_type)[[1]]

# Collapse to just names and lifeform
lookup_habitat <- cats %>% 
  group_by(LIFEFORM) %>% 
  summarize(whr = paste(unique(WHRNAME), collapse = ', '))
```

Make into Kable 
```{r}
lookup_habitat %>% 
  mutate(LIFEFORM = str_to_title(LIFEFORM)) %>% 
  rename('Habitat Type' = LIFEFORM, 'Subtypes' = whr) %>% 
  kable() %>%
  column_spec(1, width = "3cm") %>% 
  kable_styling(bootstrap_options = c("hover"), full_width = F) %>%
  row_spec(0, background = "#4A90C4", color = "white", bold = TRUE) %>%
  row_spec(seq(1, 7, 2), background = "#8EBEE2") %>%
  row_spec(seq(2, 8, 2), background = "#D6E8F5") %>%
  footnote(general = "Barren Habitat dropped due to lack of data") %>% 
  save_kable(here('Outputs', 'figures',"Habitat_Types_table.png"), zoom = 3)
```



