---
title: "Indicator Analysis "
format: html
---

```{r}
#| label: set-up
library(tidyverse) # version 2.0.0
library(sf) #1.0-21
library(here) #1.0.1
library(janitor) #2.2.1
library(stars) #0.6-8
library(terra) #1.8-42
library(arcgislayers)
library(indicspecies)
library(readxl)


```

```{r}
source(here("R", "spatial_join.R"))
```

```{r}

birds_indicator <- birds_joined %>%
  st_drop_geometry() %>%
  select(study_area,
         observation_date,
         habitat_type,
         scientific_name,
         common_name, 
         observation_count) %>%
  filter(!is.na(habitat_type), !is.na(observation_count)) %>%
  group_by(study_area, observation_date, habitat_type, scientific_name) %>%
  summarise(observation_count = sum(observation_count),
            .groups = "drop") %>%
  pivot_wider(names_from = scientific_name,
              values_from = observation_count,
              values_fill = 0)

group_vector <- birds_indicator$habitat_type

species_matrix <- birds_indicator %>%
select(-study_area, -observation_date, -habitat_type) %>%
  as.matrix()
  
birds_indicator %>% count(study_area) %>% filter(n > 1)

indval <- multipatt(species_matrix,
                    group_vector,
                    duleg = TRUE,
                    control = how(nperm = 999)) 

# Add common names back - prevents duplicate NAs 
common_names <- birds_joined %>%
  st_drop_geometry() %>%
  distinct(scientific_name, common_name)
```

```{r}
indicators <- indval$sign %>%
  rownames_to_column("species") %>%
  filter(p.value <= 0.05) %>%
  # Add common names
  left_join(common_names, by = c("species" = "scientific_name")) %>%
  pivot_longer(s.AGRICULTURE:s.WATER, names_to = "group", values_to = "member") %>%
  filter(member == 1) %>% 
  group_by(group) %>% 
  slice_max(stat, n = 5)
```

```{r}
# Load pif dataset 

pif_ca <- read_excel(here("data", "ACAD Regional 2024.06.03.xlsx")) %>% 
  filter(BCR %in% c(5, 9, 15, 32, 33))

# Join 
focal_species <- indicators %>%
  semi_join(pif_ca, by = c("species" = "Scientific Name")) %>% 
  mutate(group = str_remove(group, "s.")) 

source(here("R/testing_species_obs.R"))

focal_sp_obs <- list()

for(i in unique(focal_species$group)){
 sp_list <-  focal_species %>% 
   filter(group== i) %>% 
   select(common_name)
 
 sp_obs_habitat <- birds_joined %>% 
   st_drop_geometry() %>% 
   filter(habitat_type == i) %>% 
   filter(common_name %in% c(sp_list$common_name)) %>% 
   group_by(common_name) %>%  
   summarize(sum = sum(observation_count))

left_join(focal_species, sp_obs_habitat)

}

sp_list <-  focal_species %>% 
   filter(group == "AGRICULTURE") %>% 
   select(common_name)

sp_obs_habitat <- birds_joined %>% 
   st_drop_geometry() %>% 
   filter(habitat_type == "AGRICULTURE") %>% 
   filter(common_name %in% c(sp_list$common_name)) %>% 
   group_by(common_name) %>%  
   summarize(sum = sum(observation_count))


sp_obs_habitat(birds_joined, focal_species)

# another way

sp_obs_habitat <- birds_joined %>%
  st_drop_geometry() %>%
  inner_join(focal_species, by = c("common_name", "habitat_type" = "group")) %>%
  group_by(common_name) %>%
  summarize(sum_obs = sum(observation_count))

focal_species <- left_join(focal_species, sp_obs_habitat, by = "common_name")

# Clean up dataframe 

focal_species <- focal_species %>% 
  select(-c(index, stat, p.value, member)) 

focal_species <- focal_species %>% 
  select(-c(sum_obs.x, sum_obs.y)) %>% 
  rename(sum_obs = sum)

focal_species <- write_csv(focal_species, "focal_species_selection.csv")

test <- read_csv(here("Analysis", "focal_species_selection.csv"))

```


